import axios from 'axios'
// axios.defaults.baseURL = '../json'

export const getImg = () => axios.get('../../static/json/Data.json')
export const getHot = () => axios.get('../../static/json/Data.json')
export const getdoubanTime = () => axios.get('../../static/json/Data.json')
export const getYike = () => axios.get('../../static/json/Data.json')
export const gethomRecommend = () => axios.get('../../static/json/Data.json')
export const getFind = () => axios.get('../../static/json/Data.json')
export const getHotMovie = () => axios.get('../../static/json/movie.json')
export const getAboutShow = () => axios.get('../../static/json/movie.json')
export const getList = () => axios.get('../../static/json/movie.json')
export const getFilm = () => axios.get('../../static/json/movie.json')
export const getprobably = () => axios.get('../../static/json/movie.json')
export const getfilmItem = () => axios.get('../../static/json/movie.json')
export const getdoubanFind = () => axios.get('../../static/json/movie.json')
export const getNewBook = () => axios.get('../../static/json/read.json')
export const getImaginary = () => axios.get('../../static/json/read.json')
export const gettodayUp = () => axios.get('../../static/json/Tv.json')
export const getLocal = () => axios.get('../../static/json/activity.json')
export const getBroad = () => axios.get('../../static/json/broadcast.json')
export const getGroup = () => axios.get('../../static/json/group.json')
export const getSearch = () => axios.get('../../static/json/serach.json')
